# Frontend Configuration
url.frontend=${URL_FRONT}

# Server Configuration
server.port=${PORT:8080}

# Database Configuration (Clever Cloud MySQL)
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:portfolio_solesasia}?useSSL=true&requireSSL=true&verifyServerCertificate=false&serverTimezone=UTC
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:}

# JPA / Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect