# Frontend Configuration
url.frontend=${URL_FRONT}

# Server Configuration
server.port=${PORT:8080}

# Database Configuration (Clever Cloud MySQL)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect